# Site settings
title: Ruby backend developer | Nicolas Brousse
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nicolas-brousse.fr" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
